import './styles.scss';
import 'react-toastify/dist/ReactToastify.css';

import { storiesOf } from '@storybook/react';

import AccordionStory from './accordion';
import AutoCompleteStory from './autocomplete';
import BannersStory from './banners';
import ButtonsStory from './buttons';
import CheckboxStory from './checkbox';
import ChipStory from './chip';
import ContentHighlightStory from './content-highlight';
import DropzoneStory from './dropzone';
import FileUploaderStory from './file-uploader';
import FormsStory from './forms';
import GridStory from './grid';
import IconsStory from './icons';
import LinkStory from './link';
import NotificationStory from './notification';
import PaginationStory from './pagination';
import RadioStory from './radiobutton';
import ResponsiveTableStory from './responsive-table';
import SelectStory from './select';
import SliderStory from './slider';
import StampStory from './stamp';
import SwitchStory from './switch';
import TextStory from './text';
import TooltipStory from './tooltip';
import WizardStory from './wizard';
import TableBuilder from './table-builder';
import PopupStory from './popup';

// import AvatarStory from './avatar';
storiesOf('Accordion', AccordionStory);
storiesOf('AutoComplete', AutoCompleteStory);
storiesOf('Banners', BannersStory);
storiesOf('Button', ButtonsStory);
storiesOf('CheckBox', CheckboxStory);
storiesOf('Chip', ChipStory);
storiesOf('ContentHighlight', ContentHighlightStory);
// storiesOf('Avatar', AvatarStory);
storiesOf('Dropzone', DropzoneStory);
storiesOf('FileUploader', FileUploaderStory);
storiesOf('Forms', FormsStory);
storiesOf('Icon', IconsStory);
storiesOf('Icon', TextStory);
storiesOf('Grid', GridStory);
storiesOf('Link', LinkStory);
storiesOf('Notification', NotificationStory);
storiesOf('Pagination', PaginationStory);
storiesOf('Popup', PopupStory);
storiesOf('RadioButton', RadioStory);
storiesOf('ResponsiveTable', ResponsiveTableStory);
storiesOf('Select', SelectStory);
storiesOf('Slider', SliderStory);
storiesOf('Stamp', StampStory);
storiesOf('Switcher', SwitchStory);
storiesOf('Tooltip', TooltipStory);
storiesOf('TableBuilder', TableBuilder);
storiesOf('Wizard', WizardStory);
